### ISSUE TITLE
LUTs not appearing in dropdown with custom ComfyUI backend

### ISSUE THREAD

**Issue by bWm-nubby** [HellerCommaA/SwarmUI-PostRender#1]
I use a standalone ComfUI install which was git cloned to it's own directory rather than using one provided by SwarmUI. The following problem is due to the non-standard configuration of my system, but I wanted to share this for anyone else who may run into the same problem.

After installing this extension with the instructions in the readme and placing my .cubes in `.\SwarmUI\Models\luts` they did not show up in the dropdown for the extension or in the node in the Comfy Workflow tab. Next I tried placing them in `.\ComfyUI\models\luts` as the ProPost readme advises which caused them to show up in the PostRender LUTs dropdown, but when attempting to apply them it would still cause an error, saying the requested .cube could not be found and the selected LUT would not be applied.

**Steps to resolve:**
1. Delete the comfyui-propost directory that was installed by this extension which is located in `.\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\DLNodes`
2. Install [comfyui-propost](https://github.com/digitaljohn/comfyui-propost) as you would normally install extra nodes for ComfyUI, either through ComfyManager or by cloning it into the `.\ComfyUI\custom_nodes directory` 
3. Place .cube files in `.\ComfyUI\models\luts`
4. Restart your ComfyUI backend and refresh the SwarmUI webpage

**Comment by HellerCommaA** [comment]
Thanks. Definitely sounds like some oddities with the way your setup is. If you're running comfy inside swarm in a non-standard way, all bets from my side are off.  Glad you found a solution though. Nothing to really fix on my end, but this issue should be searchable in the issue page.
